# Generated by Django 3.2.10 on 2023-03-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='martdb',
            name='Category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
