# Generated by Django 3.2.10 on 2023-03-07 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEAPP', '0002_martdb_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='martdb',
            name='Category',
        ),
    ]
