# Generated by Django 3.2.10 on 2023-03-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEAPP', '0003_remove_martdb_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(blank=True, max_length=25, null=True)),
                ('Image', models.ImageField(upload_to='profile')),
                ('Description', models.CharField(blank=True, max_length=25, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Category', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
