# Generated by Django 3.2.10 on 2023-03-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEAPP', '0004_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Quantity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
